#!/bin/bash
### BEGIN INIT INFO
# Provides: recalbox_clcd.py & recalbox_clcd_off.py
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: I2C Lcd init script.
# Description: Starts and stops service.
### END INIT INFO

#VAR
RUN="/recalbox/scripts/recalbox_clcd.py"
RUNSTOP="/recalbox/scripts/recalbox_clcd_off.py"
BTD_PID=$(ps -eo pid,args | grep "/usr/bin/python $RUN" | grep -v grep | awk '{print $1}')

serviceStatus() {
   if [ ! -z "$BTD_PID" ]; then
      echo -e '33[0mservice recalbox_clcd.py ['$BTD_PID'] [33[33;32m OK 33[0m]'
   else
      echo -e '33[0mservice recalbox_clcd.py [33[33;31m KO 33[0m]'
   fi
}

# Carry out specific functions when asked to by the system
case "$1" in
   start)
      echo "Starting script $RUN ..."
      if [ -z "$BTD_PID" ]; then
         nice -n 19 $RUN&

         if [ $? -eq 0 ]; then
            echo -e "33[0mscript $RUN [33[33;32m STARTED 33[0m]"
         fi
      else
         echo "script $RUN already started ['$BTD_PID']!"
      fi
      #serviceStatus
   ;;
   stop)
      echo "Stopping script $RUN ..."
      if [ ! -z "$BTD_PID" ]; then
         kill $BTD_PID
         nice -n 19 $RUNSTOP& 
         if [ $? -eq 0 ]; then
            echo -e "33[0mscript $RUN [33[33;31m STOPPED 33[0m]"
         fi
      fi
      #serviceStatus
   ;;
   status)
      serviceStatus
   ;;
   *)
      echo "Usage: /etc/init.d/S97LCDInfoText {start | stop | status}"
      exit 1
   ;;
esac

exit 0
